### BASIC TENSORFLOW USAGE

NUMPY
- 텐서플로우는 numpy 를 거의 따라감
- 모든 명령어, 함수도 numpy 와 같게 변하는중

CONSTANT
- 상수
- 텐서 값은 원래 바로 볼 수 없음
- 이를 보기 위해 Session 이 필요(매직키와비슷). sess.run으로 출력

VARIABLES
- 중요!!!
- 바뀌는 값
- NN 에서는 weights 가 됨
- 어느 타입으로 초기화할지 정해줘야 함 ( `tf.random_normal()` )
- `sess.run(weight)` 하면 나올 것 같지만, 에러가 나옴 / 왜냐면 실제로 초기화를 하는 명령어가 없기 때문
 - `init = tf.global_variables_initializer()` 로 초기화 한번 해줘야함
 - VARIABLES 은 초기화를 하지 않으면 값이 들어가지 않음
 
PLACEHODLERS
- 중요!!!
- 공장(GRAPH)안에 변하는 값(VARIABLE)을 집어넣는 통로(PLACEHODLER)
- `tf.placeholder(tf.float32, [None, 5])`
 - `None` : 정해지지 않음 ( 미니배치 갯수를 알아서 잡아주기 위해서 )
 - 데이터 갯수에 해당하는 곳에 None 을 지정해줌
- `feed_dict={x: data}` : x 에 data 를 넣어라 ( tf 문법임 )

#### LOAD PACKAGE

In [1]:
import numpy as np
import tensorflow as tf
print ("PAKAGES LOADED")

PAKAGES LOADED


#### SESSION

In [2]:
sess = tf.Session()
print ("OPEN SESSION")

OPEN SESSION


#### TF CONSTANT

In [3]:
def print_tf(x):
    print("TYPE IS \n %s" % (type(x)))
    print("VALUE IS \n %s" % (x))
hello = tf.constant("HELLO. IT'S ME. ")
print_tf(hello)

TYPE IS 
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS 
 Tensor("Const:0", shape=(), dtype=string)


#### TO MAKE THINGS HAPPEN

In [4]:
hello_out = sess.run(hello)
print_tf(hello_out)

TYPE IS 
 <class 'bytes'>
VALUE IS 
 b"HELLO. IT'S ME. "


#### OTHER TYPES OF CONSTANT

In [5]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print_tf(a)
print_tf(b)

TYPE IS 
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS 
 Tensor("Const_1:0", shape=(), dtype=float32)
TYPE IS 
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS 
 Tensor("Const_2:0", shape=(), dtype=float32)


#### AGAIN, RUN

In [6]:
a_out = sess.run(a)
b_out = sess.run(b)
print_tf(a_out)
print_tf(b_out)

TYPE IS 
 <class 'numpy.float32'>
VALUE IS 
 1.5
TYPE IS 
 <class 'numpy.float32'>
VALUE IS 
 2.5


#### OPERATORS WITH FIXED INPUTS

In [7]:
a_plus_b = tf.add(a, b)
print_tf(a_plus_b)

TYPE IS 
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS 
 Tensor("Add:0", shape=(), dtype=float32)


#### RUN OPERATOR

In [8]:
a_plus_b_out = sess.run(a_plus_b)
print_tf(a_plus_b_out)

TYPE IS 
 <class 'numpy.float32'>
VALUE IS 
 4.0


In [9]:
a_mul_b = tf.mul(a, b) # tf.multiply in v1.0
a_mul_b_out = sess.run(a_mul_b)
print_tf(a_mul_b_out)

TYPE IS 
 <class 'numpy.float32'>
VALUE IS 
 3.75


#### VARIABLES

In [10]:
weight = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
print_tf(weight)

TYPE IS 
 <class 'tensorflow.python.ops.variables.Variable'>
VALUE IS 
 Tensor("Variable/read:0", shape=(5, 2), dtype=float32)


#### GET VALUES?

In [11]:
weight_out = sess.run(weight)
print_tf(weight_out)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: _send_Variable_0 = _Send[T=DT_FLOAT, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=4029784950310247942, tensor_name="Variable:0", _device="/job:localhost/replica:0/task:0/cpu:0"](Variable)]]

#### WHY DOES THIS ERROR OCCURS?

In [12]:
init = tf.global_variables_initializer()
sess.run(init)
print("INITIALIZING ALL VARIABLES")

INITIALIZING ALL VARIABLES


#### ONCE INITIALIZED

In [13]:
weight_out = sess.run(weight)
print_tf(weight_out)

TYPE IS 
 <class 'numpy.ndarray'>
VALUE IS 
 [[ 0.06090027  0.03269998]
 [ 0.01535145 -0.17756259]
 [ 0.00167872  0.086207  ]
 [-0.0959048   0.13228513]
 [-0.13128577 -0.05244499]]


#### PLACEHOLDERS

In [14]:
x = tf.placeholder(tf.float32, [None, 5])
print_tf(x)

TYPE IS 
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS 
 Tensor("Placeholder:0", shape=(?, 5), dtype=float32)


#### OPERATION WITH VARIABLES AND PLACEHOLDERS

In [15]:
oper = tf.matmul(x, weight)
print_tf(oper)

TYPE IS 
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS 
 Tensor("MatMul:0", shape=(?, 2), dtype=float32)


#### FEED_DICT PLACEHOLDER

In [16]:
data = np.random.rand(1, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS 
 <class 'numpy.ndarray'>
VALUE IS 
 [[-0.07318713  0.06580727]]


#### BATCHSIZE CAN VARY

In [17]:
data = np.random.rand(2, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS 
 <class 'numpy.ndarray'>
VALUE IS 
 [[-0.03301957  0.03382742]
 [-0.05511223  0.08873765]]
